FROM          khrisrichardson/salt-minion:latest
MAINTAINER    Khris Richardson <khris.richardson@gmail.com>

EXPOSE        4369
EXPOSE        8091
EXPOSE        8092
EXPOSE        11209
EXPOSE        11210
EXPOSE        21100
