FROM          salt-minion:latest
MAINTAINER    Khris Richardson <khris.richardson@gmail.com>

EXPOSE        2003
EXPOSE        2003/udp
EXPOSE        4444
EXPOSE        5551
EXPOSE        8083
EXPOSE        8084
EXPOSE        8086
EXPOSE        8090
EXPOSE        8099
